### ISSUE TITLE
Transform functions do not maintain autoStart flag

### ISSUE THREAD

**Issue by rubensworks** [RubenVerborgh/AsyncIterator#2]
Consider the following example:
```
const AsyncIterator = require('AsyncIterator');

const it = new AsyncIterator.BufferedIterator({ autoStart: false });
let counter = 0;
it._read = function(count, cb) {
  console.log('Reading ' + count);
  for (let i = 0; i < count; i++) {
    this._push(counter++);
  }
  cb();
};

console.log('Initialized buffered iterator!');

const it2 = it.map((i) => i * 10);

console.log('Initialized mapped iterator!');
```

As the `autoStart` parameter of `it` is set to `false`, no elements will be buffered until a data listener is attached.
However, when the iterator is transformed (for example using `map`), then this `autoStart` parameter is not inherited.

For this example, the following output will be produced:
```
Initialized buffered iterator!
Initialized mapped iterator!
Reading 4
Reading 1
Reading 1
Reading 1
Reading 1
```

The expected behaviour would be that no elements are produced until a data listener is attached to either `it` or `it2`.

**Comment by RubenVerborgh** [comment]
I've been thinking a bit about this, and I'm not sure what the desired behavior is:

1. On the one hand, one could argue that, since the source stream is started lazily, so should the transformed stream.

2. On the other hand, one could argue that, by calling `transform` on the source stream, you are essentially starting it.

I started thinking that this second behavior is actually more natural.
So in cases where you want the first behavior, you would need to pass the `autoStart: false` attribute to the `.transform` function (which isn't available through shorthands such as `map`).

Given the above arguments, what do you think?
I've created a branch `fix-transform-autostart` which has `autoStart: false` behavior as the default for `transform` and its helpers so you can compare. (That said, it's the only place where `autoStart` would not be true by default.) The exact behavior you suggest here, having `autoStart` equal to the source, could also be implemented, but would complicate matters (so I first want to have the discussion about its necessity).

-----

Minor nit:

> The expected behaviour would be that no elements are produced until a data listener is attached to either it or it2.

You shouldn't read `it` after you have mapped it (as stated in the docs).

**Comment by rubensworks** [comment]
I think both options make sense.

I'm now just thinking from the view of Comunica, where streams may potentially be very expensive to start (HTTP requests). In comunica, we create these streams lazily, and apply transformations on them. The most logical thing in this case would be that streams start producing streams from the moment they actually become required, as there are cases where they might never be consumed (for example, when a pattern with 0 count is found in the same BGP).

In any case, I think optional options on the transform functions would already help a lot. Currently I have to wrap all transformations in a [promise proxy](https://www.npmjs.com/package/asynciterator-promiseproxy), which is a bit too verbose...

EDIT: Just thinking about it a bit more, and I think that from an outsider's perspective, the result of a transform function perhaps does not even have to be a buffered stream. (for performance-reasons, I understand that you _do_ want this in some cases though)

**Comment by RubenVerborgh** [comment]
> In any case, I think optional options on the transform functions would already help a lot.

So this is currently already implemented in `.transform`, to which you can pass an `autoStart` option. So instead of `.map(f)`, just call `.transform({ map: f, autostart: false })`. Would that already help?

I would add this to the `.map` method as well, but its signature is problematic. Currently, the signature is `#map(callback, self)` to mimic the corresponding `Array` method. However, I expect the `self` parameter to not be used that often given arrow functions in ES6. Adding in options would require the signature to change into `#map(callback, self, options)`, but then you'd need to supply the `self`—can't make it optional, because we can't distinguish between `self` and `options`.

What I could do is add `.lazyMap` methods.

> EDIT: Just thinking about it a bit more, and I think that from an outsider's perspective, the result of a transform function perhaps does not even have to be a buffered stream.

You're right. This library adds in `BufferedStream` through inheritance for simplicity; however, it could also have made sense to have it as a mix-in, so you can decide for any stream whether or not it is buffered.

But yeah, look at the relative complexity of `BufferedIterator`, and especially its tests, and you'll understand why :wink:

**Comment by rubensworks** [comment]
> So instead of .map(f), just call .transform({ map: f, autostart: false }). Would that already help?

Yes, that would actually work, not sure why I didn't do this initially...

A `lazyMap` might indeed be nice to have, but not essential with with `transform` workaround.

**Comment by RubenVerborgh** [comment]
Okay, thanks!
